#!/usr/bin/env python3
# mk_tiny_elf.py — W16: 生成最小 ELF (打一行后 exit; exec-from-mem 用)
# 输出: sdk/linux/tiny_elf.h (C 数组, 供 m127 demo 内嵌)
import struct

CODE = bytes([
    0x48, 0xC7, 0xC0, 0x01, 0x00, 0x00, 0x00,  # mov rax, 1
    0x48, 0xC7, 0xC7, 0x01, 0x00, 0x00, 0x00,  # mov rdi, 1
    0x48, 0x8D, 0x35, 0x00, 0x00, 0x00, 0x00,  # lea rsi, [rip+0] (msg 距离后填)
    0x48, 0xC7, 0xC2, 0x0F, 0x00, 0x00, 0x00,  # mov rdx, 15
    0x0F, 0x05,                                # syscall
    0x48, 0xC7, 0xC0, 0x3C, 0x00, 0x00, 0x00,  # mov rax, 60
    0x48, 0x31, 0xFF,                          # xor rdi, rdi
    0x0F, 0x05,                                # syscall
])
MSG = b"exec-child-ok\n"  # 15B
PAT = 0x400000  # 装载基址
DATA = CODE + MSG

# lea rsi 的 rel32: message_offset - (after_lea_offset)
lea_off = 14
code_off = len(CODE)
rel = (code_off) - (lea_off + 7)  # lea_rsi 指令后 rip
b = bytearray(DATA)
b[lea_off + 3:lea_off + 7] = struct.pack("<i", rel)

file_off = 64 + 56  # Ehdr + Phdr
ehdr = struct.pack(
    "<16sHHIQQQIHHHHHH",
    b"\x7fELF" + bytes([2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    2, 62, 1, PAT, 64, 0, 0,   # e_phoff = 64 (phdr 紧跟 ehdr)
    64, 56, 1, 0, 0, 0,
)
phdr = struct.pack(
    "<IIQQQQQQ",
    1, 5, file_off, PAT, PAT, len(b), len(b), 0x1000,
)
elf = ehdr + phdr + bytes(b)
assert elf[0:4] == b"\x7fELF"
assert len(elf) == file_off + len(b)

lines = [f"/* tiny_elf.h — generated by tools/mk_tiny_elf.py (W16) */"]
lines.append("static const unsigned char tiny_elf[] = {")
for i in range(0, len(elf), 12):
    chunk = elf[i:i + 12]
    lines.append("    " + ", ".join(f"0x{x:02x}" for x in chunk) + ",")
lines.append("};")
lines.append(f"static const unsigned long tiny_elf_len = {len(elf)}UL;")
with open("sdk/linux/tiny_elf.h", "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"mk_tiny_elf: wrote sdk/linux/tiny_elf.h ({len(elf)} bytes)")
